### ISSUE TITLE
BASIC Anywhere Machine

### ISSUE THREAD

**Issue by CharlieJV** [DualBrain/gotBASIC#4]
G'day,

First: this is really good stuff.  Anything anybody does to give BASIC some love ... rock'n roll !

If it fits your mission and is of interest, here is my project:  [BASIC Anywhere Machine](https://sites.google.com/view/basicanywheremachine)

It is an enhanced version of [wwwBASIC](https://github.com/google/wwwbasic) (a BASIC meant for the web), embedded in (or hosted by) and enhanced by [TiddlyWiki](https://tiddlywiki.com/).

So a single-file HTML, with IDE, tools, the interpreter, the BASIC programs, on-line/off-line, with various BASIC program export options.

[Give it a spin](https://basicanywheremachine.neocities.org/).  And view the work-in-progress [programming reference](https://basicanywheremachine.neocities.org/BAM_ProgReference.html).

Cheers and best regards!

**Comment by CharlieJV** [comment]
G'day,

I forever struggle trying to find the right words to describe things.  If of any use and of any interest, here's my most recent attempt:

Links:  [BASIC Anywhere Machine](https://basicanywheremachine.neocities.org/BAM_IDE.html), [Project Web Site](https://basicanywheremachine.neocities.org/), [Programming Reference](https://basicanywheremachine.neocities.org/BAM_ProgReference.html)

BASIC Anywhere Machine (BAM) is a fully self-contained, single-file, zero-install environment for BASIC programming in a web browser, equally at home offline and online.

BAM, a [TiddlyWiki](https://tiddlywiki.com/), hosts a modified version of [wwwBASIC](https://github.com/google/wwwbasic) (a BASIC interpreter written in javascript), a CodeMirror-enhanced IDE, BASIC programs (BASIC programs are stored in the wiki), and various tools including many ways of exporting BASIC programs for sharing and for running on the web or locally.

As a TiddlyWiki, BAM has all of the benefits inherent to TiddlyWiki: [future proof](https://tiddlywiki.com/#Future%20Proof), adaptable, expandable (via plugins), ridiculously easy to customize, and extremely good at capturing, organising and sharing content (BASIC programs and anything imaginable.)  Your copy of BAM and your programs of today, all in one file, should all still work fifteen years from now because BAM is using standards-compliant HTML, CSS, and javascript.

Store BAM anywhere: SD card, USB Thumbdrive, local drive, network drive, hosted file storage service.

Create straight-up BASIC programs.  Create programs that are dynamically altered by TiddlyWiki just before execution.  Create programs designed to interact with TiddlyWiki widgets and content during execution.

Sample exports of the "spheres" program:  [View the source code](https://basicanywheremachine.neocities.org/sample_programs/Spheres.bas.html).  [Run the program](https://basicanywheremachine.neocities.org/sample_programs/Spheres.run.html).

**Comment by DualBrain** [comment]
This looks pretty awesome!  Feel free to take a look at https://gotbasic.com/bam.html

**Comment by CharlieJV** [comment]
Hey, thank-you much!

And thanks for helping to keep BASIC in the limelight !
