### ISSUE TITLE
GFA BASIC

### ISSUE THREAD

**Issue by mva1985** [DualBrain/gotBASIC#7]
First, just wanted to say that I **love** gotbasic.com

Second, I haven't seen anything mentioned about GFA BASIC
and just wanted to provide a link... http://gfabasic32.blogspot.com/

My apologies if you already have it listed somewhere

Thanks again for the website.

**Comment by DualBrain** [comment]
Thank you for your kind words, it is really appreciated.

I've updated the site to now include GFA.
